/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.vitevskii.gradle;

import java.math.BigDecimal;

public class App {

    public final static Product PRODUCT = new Product("Phone", "A nice phone", new BigDecimal(1000));

    public static void main(String[] args) {
        System.out.println(PRODUCT.getName() + ", " + PRODUCT.getDescription() + ", " + PRODUCT.getPrice());
    }
}
